name: Update EPG File CROn.xml

on:
  schedule:
    - cron: '45 5 * * *'
    - cron: '45 13 * * *'
    - cron: '45 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove existing CROn.xml
      run: |
        rm -f ./CROn.xml
        git rm --ignore-unmatch CROn.xml

    - name: Download the new EPG file
      run: |
        wget https://www.open-epg.com/files/croatia.xml.gz

    - name: Decompress the new EPG file
      run: |
        gunzip croatia.xml.gz

    - name: Format the EPG file
      run: |
        sed -i 's/<title/\n<title/g' croatia.xml
        sed -i 's/<sub/\n<sub/g' croatia.xml
        sed -i 's/<desc/\n<desc/g' croatia.xml
        sed -i 's/<episode/\n<episode/g' croatia.xml
        sed -i 's/<\/programme>/\n<\/programme>/g' croatia.xml

    - name: Save the formatted file as CROn.xml
      run: |
        mv croatia.xml ./CROn.xml

    - name: Commit and force-push the changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "GitHub Actions"
        git add CROn.xml
        git commit -m "Update EPG file" --allow-empty
        git push origin main --force
